# Generated by Django 4.1.5 on 2023-03-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mobile_number', models.IntegerField()),
                ('email_address', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('confirm_password', models.CharField(blank=True, max_length=100, null=True)),
                ('user_gender', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
